# vim: ft=dosini
[main]
font=FiraCode Nerd Font:size=12
font-size-adjustment=1.0 # default 0.5
dpi-aware=false
locked-title=no

[colors]
# Reference: https://github.com/tokyo-night/tokyo-night-vscode-theme/blob/master/themes/tokyo-night-light-color-theme.json
background=d6d8df
foreground=343b58
regular0=343b58
regular1=8c4351
regular2=33635c
regular3=8f5e15
regular4=2959aa
regular5=7b43ba
regular6=006c86
regular7=707280
bright0=343b58
bright1=8c4351
bright2=33635c
bright3=8f5e15
bright4=2959aa
bright5=7b43ba
bright6=006c86
bright7=707280

jump-labels=343b58 e19d37 # brighter yellow than regular3

[colors2]
alpha=0.95
background=1a1b26
foreground=c0caf5
regular0=15161e
regular1=f7768e
regular2=9ece6a
regular3=e0af68
regular4=7aa2f7
regular5=bb9af7
regular6=7dcfff
regular7=a9b1d6
bright0=414868
bright1=f7768e
bright2=9ece6a
bright3=e0af68
bright4=7aa2f7
bright5=bb9af7
bright6=7dcfff
bright7=c0caf5
