# for excluding externals, add them to ~/.local/share/chezmoi/.chezmoiignore

# speed up daily usage, only check externals if environment variable `ONLINE` is set
# https://github.com/twpayne/chezmoi/discussions/4178#discussioncomment-11719758
{{- if not ( not (env "ONLINE") ) }}

# dynamic name resolution for golang based binaries, won't work on Windows
{{- if and (ne .chezmoi.os "windows") (ne .host.chassis "container") }}
# ArchLinux provides those packages already
{{- if and (ne .host.osId "linux-arch") (ne .host.osId "linux-cachyos") }}
[".local/bin/age"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "FiloSottile/age" ( printf "age-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "age"
    stripComponents = 1
    executable = true
    private = true
[".local/bin/age-inspect"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "FiloSottile/age" ( printf "age-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "age-inspect"
    stripComponents = 1
    executable = true
    private = true
[".local/bin/age-keygen"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "FiloSottile/age" ( printf "age-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "age-keygen"
    stripComponents = 1
    executable = true
    private = true
[".local/bin/age-plugin-batchpass"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "FiloSottile/age" ( printf "age-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "age-plugin-batchpass"
    stripComponents = 1
    executable = true
    private = true
[".local/bin/age-plugin-yubikey"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "str4d/age-plugin-yubikey" "age-plugin-yubikey-*-x86_64-linux.tar.gz" | quote }}
    path = "age-plugin-yubikey"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/age-plugin-tpm"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "Foxboron/age-plugin-tpm" ( printf "age-plugin-tpm-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "age-plugin-tpm"
    stripComponents = 1
    executable = true
    private = true
[".local/bin/direnv"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "direnv/direnv" ( printf "direnv.%s-%s" .chezmoi.os .chezmoi.arch ) | quote }}
    executable = true
    private = true
[".local/bin/fzf"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "junegunn/fzf" ( printf "fzf-*-%s_%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "fzf"
    private = true
    executable = true
[".local/bin/gh"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "cli/cli" ( printf "gh_*_%s_%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "gh"
    stripComponents = 2
    private = true
    executable = true
[".local/bin/hcloud"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "hetznercloud/cli" "hcloud-linux-amd64.tar.gz" | quote }}
    path = "hcloud"
    private = true
    executable = true
[".local/bin/mlr"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "johnkerl/miller" ( printf "miller-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "mlr"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/rclone"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "rclone/rclone" ( printf "rclone-*-%s-%s.zip" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "rclone"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/restic"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "restic/restic" ( printf "restic_*_%s_%s.bz2" .chezmoi.os .chezmoi.arch ) | quote }}
    filter.command = "bunzip2"
    private = true
    executable = true
[".local/bin/sops"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "getsops/sops" ( printf "sops-*.%s.%s" .chezmoi.os .chezmoi.arch ) | quote }}
    private = true
    executable = true
[".local/bin/yq"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "mikefarah/yq" ( printf "yq_%s_%s" .chezmoi.os .chezmoi.arch ) | quote }}
    private = true
    executable = true

{{- if eq .chezmoi.os "linux" }}
[".local/bin/nnn"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "jarun/nnn" "nnn-nerd-static-*.tar.gz" | quote }}
	path = "nnn-nerd-static"
	private = true
	executable = true

{{- if eq .chezmoi.arch "amd64" }}
[".local/bin/atuin"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "atuinsh/atuin" "atuin-x86_64-unknown-linux-musl.tar.gz" | quote }}
	path = "atuin"
	stripComponents = 1
	executable = true
	private = true
[".local/bin/bat"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "sharkdp/bat" "bat-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "bat"
    private = true
    executable = true
[".local/bin/deno"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "denoland/deno" "deno-x86_64-unknown-linux-gnu.zip" | quote }}
    path = "deno"
    private = true
    executable = true
[".local/bin/delta"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "dandavison/delta" "delta-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "delta"
    private = true
    executable = true
[".local/bin/duf"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "muesli/duf" "duf_*_linux_x86_64.tar.gz" | quote }}
    path = "duf"
    executable = true
    private = true
[".local/bin/eza"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "eza-community/eza" "eza_x86_64-unknown-linux-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "eza"
    private = true
    executable = true
[".local/bin/fd"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "sharkdp/fd" "fd-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "fd"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/jj"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "jj-vcs/jj" "jj-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "jj"
    private = true
    executable = true
[".local/bin/jless"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "PaulJuliusMartinez/jless" "jless-*-x86_64-unknown-linux-gnu.zip" | quote }}
    path = "jless"
    private = true
    executable = true
[".local/bin/just"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "casey/just" "just-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
	path = "just"
    executable = true
	private = true
[".local/bin/k9s"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "derailed/k9s" "k9s_Linux_amd64.tar.gz" | quote }}
    path = "k9s"
    private = true
    executable = true
[".local/bin/lazygit"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" "lazygit_*_linux_x86_64.tar.gz" | quote }}
    path = "lazygit"
    private = true
    executable = true
[".local/bin/micro"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "zyedidia/micro" "micro-*-linux64-static.tar.gz" | quote }}
    stripComponents = 1
    path = "micro"
    private = true
    executable = true
[".local/bin/mise"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "jdx/mise" "mise-*-linux-x64-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "bin/mise"
    private = true
    executable = true
[".local/bin/navi"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "denisidoro/navi" "navi-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "navi"
    private = true
    executable = true
[".local/bin/nitropy"]
    type = "archive-file"
    url = "https://github.com/Nitrokey/pynitrokey/releases/download/v0.11.2/nitropy-v0.11.2-x64-linux-binary.tar.gz"
    checksum.sha256 = "e1a3caf2d7c918fd7401d91eb82b50277686e308d14541cdba5dd3e1bd7872cb"
    path = "nitropy-v0.11.2-x64-linux-binary"
    private = true
    executable = true
[".local/bin/rg"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "BurntSushi/ripgrep" "ripgrep-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
	path = "rg"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/starship"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "starship/starship" "starship-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "starship"
    private = true
    executable = true
{{ if and (eq .host.isGui true) (eq .host.guiSession "sway") -}}
[".local/bin/sway-previous-focus"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "macedigital/sway-previous-focus" "sway-previous-focus_Linux_x86_64.tar.gz" | quote }}
    path = "sway-previous-focus"
    executable = true
    private = true
{{ end -}}
[".local/bin/uv"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "astral-sh/uv" "uv-x86_64-unknown-linux-musl.tar.gz" | quote }}
	stripComponents = 1
	path = "uv"
	private = true
	executable = true
[".local/bin/uvx"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "astral-sh/uv" "uv-x86_64-unknown-linux-musl.tar.gz" | quote }}
	stripComponents = 1
	path = "uvx"
	private = true
	executable = true
[".local/bin/xan"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "medialab/xan" "xan-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "xan"
    private = true
    executable = true
[".local/bin/zellij"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "zellij-org/zellij" "zellij-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "zellij"
    executable = true
    private = true
[".local/bin/zoxide"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "ajeetdsouza/zoxide" "zoxide-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "zoxide"
    executable = true
    private = true
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
