# for excluding externals, add them to ~/.local/share/chezmoi/.chezmoiignore

# speed up daily usage, only check externals if environment variable `ONLINE` is set
# https://github.com/twpayne/chezmoi/discussions/4178#discussioncomment-11719758
{{- if not ( not (env "ONLINE") ) }}

# dynamic name resolution for golang based binaries, won't work on Windows
{{- if ne .chezmoi.os "windows" }}
[".local/bin/direnv"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "direnv/direnv" ( printf "direnv.%s-%s" .chezmoi.os .chezmoi.arch ) | quote }}
    executable = true
    private = true
[".local/bin/devbox"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "jetify-com/devbox" ( printf "devbox_*_%s_%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "devbox"
    executable = true
    private = true
[".local/bin/dyff"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "homeport/dyff" ( printf "dyff_*_%s_%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "dyff"
    executable = true
    private = true
[".local/bin/fzf"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "junegunn/fzf" ( printf "fzf-*-%s_%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "fzf"
    private = true
    executable = true
[".local/bin/gh"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "cli/cli" ( printf "gh_*_%s_%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "gh"
    stripComponents = 2
    private = true
    executable = true
[".local/bin/grype"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "anchore/grype" ( printf "grype_*_%s_%s.tar.gz" .chezmoi.os .chezmoi.arch) | quote }}
	path = "grype"
	private = true
	executable = true
[".local/bin/jd"]
	type = "file"
	url = {{ gitHubLatestReleaseAssetURL "josephburnett/jd" ( printf "jd-%s-%s" .chezmoi.arch .chezmoi.os ) | quote }}
	executable = true
	private = true
[".local/bin/mlr"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "johnkerl/miller" ( printf "miller-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "mlr"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/rclone"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "rclone/rclone" ( printf "rclone-*-%s-%s.zip" .chezmoi.os .chezmoi.arch ) | quote }}
    path = "rclone"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/restic"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "restic/restic" ( printf "restic_*_%s_%s.bz2" .chezmoi.os .chezmoi.arch ) | quote }}
    filter.command = "bunzip2"
    private = true
    executable = true
[".local/bin/yq"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "mikefarah/yq" ( printf "yq_%s_%s" .chezmoi.os .chezmoi.arch ) | quote }}
    private = true
    executable = true

{{- if eq .chezmoi.os "linux" }}
[".local/bin/nnn"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "jarun/nnn" "nnn-nerd-static-*.tar.gz" | quote }}
	path = "nnn-nerd-static"
	private = true
	executable = true

{{- if eq .chezmoi.arch "amd64" }}
[".local/bin/atuin"]
	type = "file"
	url = {{ gitHubLatestReleaseAssetURL "atuinsh/atuin" "atuin-x86_64-unknown-linux-musl.tar.gz" | quote }}
	executable = true
	private = true
[".local/bin/bat"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "sharkdp/bat" "bat-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "bat"
    private = true
    executable = true
[".local/bin/delta"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "dandavison/delta" "delta-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "delta"
    private = true
    executable = true
[".local/bin/eza"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "eza-community/eza" "eza_x86_64-unknown-linux-musl.tar.gz" | quote }}
    stripComponents = 1
    path = "eza"
    private = true
    executable = true
[".local/bin/fd"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "sharkdp/fd" "fd-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "fd"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/jless"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "PaulJuliusMartinez/jless" "jless-*-x86_64-unknown-linux-gnu.zip" | quote }}
    path = "jless"
    private = true
    executable = true
[".local/bin/lazygit"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" "lazygit_*_linux_x86_64.tar.gz" | quote }}
    path = "lazygit"
    private = true
    executable = true
[".local/bin/micro"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "zyedidia/micro" "micro-*-linux64-static.tar.gz" | quote }}
    stripComponents = 1
    path = "micro"
    private = true
    executable = true
[".local/bin/rg"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "BurntSushi/ripgrep" "ripgrep-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
	path = "rg"
    stripComponents = 1
    private = true
    executable = true
[".local/bin/starship"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "starship/starship" "starship-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "starship"
    private = true
    executable = true
[".local/bin/sway-previous-focus"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "macedigital/sway-previous-focus" "sway-previous-focus_Linux_x86_64.tar.gz" | quote }}
    path = "sway-previous-focus"
    executable = true
    private = true
[".local/bin/uv"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "astral-sh/uv" "uv-x86_64-unknown-linux-musl.tar.gz" | quote }}
	stripComponents = 1
	path = "uv"
	private = true
	executable = true
[".local/bin/uvx"]
	type = "archive-file"
	url = {{ gitHubLatestReleaseAssetURL "astral-sh/uv" "uv-x86_64-unknown-linux-musl.tar.gz" | quote }}
	stripComponents = 1
	path = "uvx"
	private = true
	executable = true
[".local/bin/xan"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "medialab/xan" "xan-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "xan"
    private = true
    executable = true
[".local/bin/zellij"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "zellij-org/zellij" "zellij-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "zellij"
    executable = true
    private = true
[".local/bin/zoxide"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "ajeetdsouza/zoxide" "zoxide-*-x86_64-unknown-linux-musl.tar.gz" | quote }}
    path = "zoxide"
    executable = true
    private = true
# ArchLinux provides those packages already
{{- if and (hasKey .chezmoi.osRelease "id") (not (eq .chezmoi.osRelease.id "arch")) }}
[".local/bin/age-plugin-yubikey"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "str4d/age-plugin-yubikey" "age-plugin-yubikey-*-x86_64-linux.tar.gz" | quote }}
    path = "age-plugin-yubikey"
    stripComponents = 1
    private = true
    executable = true
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
