# for excluding externals, add them to ~/.local/share/chezmoi/.chezmoiignore
{{- if eq .chezmoi.os "linux" }}
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/share/fonts/FiraCodeNerdFont-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.tar.xz"
    path = "FiraCodeNerdFont-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "def4b29f7aa0620a7fa12edb28197a2697680b5e21636fa3dcc602e08ae13bc4"
[".local/share/fonts/MesloLGLNerdFontPropo-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.tar.xz"
    path = "MesloLGLNerdFontPropo-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "1abdaf5542b75a51d75de6373148a8e401b28eda88e6c90f243fb6114fd659ea"
# ArchLinux provides those packages already
{{- if and (hasKey .chezmoi.osRelease "id") (not (eq .chezmoi.osRelease.id "arch")) }}
[".local/bin/age-plugin-yubikey"]
    type = "archive-file"
    url = "https://github.com/str4d/age-plugin-yubikey/releases/download/v0.5.0/age-plugin-yubikey-v0.5.0-x86_64-linux.tar.gz"
    checksum.sha256 = "019b35a13fc81be56d73d0723db0a2082fbd04c936c2c6836381111f7f51b2c3"
    path = "age-plugin-yubikey/age-plugin-yubikey"
    mode = "0700"
# Void Linux has all these
{{- if not ( eq .chezmoi.osRelease.id "void" ) }}
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/download/v0.18.23/eza_x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "8d0f3204795c04ed50060eb87d264770271658ee7964b21dd83f7119110e1166"
    stripComponents = 1
    path = "eza"
    mode = "0700"
[".local/bin/fd"]
    type = "archive-file"
    url = "https://github.com/sharkdp/fd/releases/download/v10.1.0/fd-v10.1.0-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "f8fa73aa005e71598c1cdbb03ae6979fd016d5a8aaf92ee84ed6f8f186c58ead"
    path = "fd-v10.1.0-x86_64-unknown-linux-musl/fd"
    mode = "0700"
[".local/bin/jless"]
    type = "archive-file"
    url = "https://github.com/PaulJuliusMartinez/jless/releases/download/v0.9.0/jless-v0.9.0-x86_64-unknown-linux-gnu.zip"
    checksum.sha256 = "a1e0eb63ef347adc649989ac5c7d2dc896df6d494622b953c86e3a248e733a93"
    path = "jless"
    mode = "0700"
[".local/bin/lazygit"]
    type = "archive-file"
    url = "https://github.com/jesseduffield/lazygit/releases/download/v0.43.1/lazygit_0.43.1_Linux_x86_64.tar.gz"
    checksum.sha256 = "dee1c7a2dc09801b4d610fffd6ba33a8187fa9ec512696108bc68aa1557f7aee"
    path = "lazygit"
    mode = "0700"
[".local/bin/k9s"]
    type = "archive-file"
    url = "https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Linux_amd64.tar.gz"
    checksum.sha256 = "33c31bf5feba292b59b8dabe5547cb52ab565521ee5619b52eb4bd4bf226cea3"
    path = "k9s"
    mode = "0700"
[".local/bin/rg"]
    type = "archive-file"
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "f84757b07f425fe5cf11d87df6644691c644a5cd2348a2c670894272999d3ba7"
    path = "ripgrep-14.1.0-x86_64-unknown-linux-musl/rg"
    mode = "0700"
[".local/bin/yq"]
    type = "file"
    url = "https://github.com/mikefarah/yq/releases/download/v4.42.1/yq_linux_amd64"
    checksum.sha256 = "1a95960dddd426321354d58d2beac457717f7c49a9ec0806749a5a9e400eb45e"
    mode = "0700"
    executable = true
{{- end }}
{{- end }}
{{- end }}
