# for excluding externals, add them to ~/.local/share/chezmoi/.chezmoiignore
{{- if eq .chezmoi.os "linux" }}
[".local/share/fonts/FiraCodeNerdFont-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraCode.tar.xz"
    path = "FiraCodeNerdFont-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "7c64c44d7e530b25faf23904e135e9d1ff0339a92ee64e35e7da9116aa48af67"
[".local/share/fonts/MesloLGLNerdFontPropo-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Meslo.tar.xz"
    path = "MesloLGLNerdFontPropo-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "6ad716ed719e2c97794abd5856a90c6131c406606b249debdc83b04ae11f4cb7"
# ArchLinux provides those packages already
{{- if and (hasKey .chezmoi.osRelease "id") (not (eq .chezmoi.osRelease.id "arch")) }}
[".local/bin/age-plugin-yubikey"]
    type = "archive-file"
    url = "https://github.com/str4d/age-plugin-yubikey/releases/download/v0.5.0/age-plugin-yubikey-v0.5.0-x86_64-linux.tar.gz"
    checksum.sha256 = "019b35a13fc81be56d73d0723db0a2082fbd04c936c2c6836381111f7f51b2c3"
    path = "age-plugin-yubikey/age-plugin-yubikey"
    mode = "0700"
# Void Linux has all these
{{- if not ( eq .chezmoi.osRelease.id "void" ) }}
[".local/bin/bat"]
    type = "archive-file"
    url = "https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "d39a21e3da57fe6a3e07184b3c1dc245f8dba379af569d3668b6dcdfe75e3052"
    stripComponents = 1
    path = "bat"
    mode = "0700"
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/download/v0.20.9/eza_x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "d99e62b5c386d0bc9c1c6ff0fd2b1b9ceea4f0ba7a6c9de8f02244d1ec4837e0"
    stripComponents = 1
    path = "eza"
    mode = "0700"
[".local/bin/fd"]
    type = "archive-file"
    url = "https://github.com/sharkdp/fd/releases/download/v10.2.0/fd-v10.2.0-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "d9bfa25ec28624545c222992e1b00673b7c9ca5eb15393c40369f10b28f9c932"
    path = "fd-v10.2.0-x86_64-unknown-linux-musl/fd"
    mode = "0700"
[".local/bin/jless"]
    type = "archive-file"
    url = "https://github.com/PaulJuliusMartinez/jless/releases/download/v0.9.0/jless-v0.9.0-x86_64-unknown-linux-gnu.zip"
    checksum.sha256 = "a1e0eb63ef347adc649989ac5c7d2dc896df6d494622b953c86e3a248e733a93"
    path = "jless"
    mode = "0700"
[".local/bin/lazygit"]
    type = "archive-file"
    url = "https://github.com/jesseduffield/lazygit/releases/download/v0.44.1/lazygit_0.44.1_Linux_x86_64.tar.gz"
    checksum.sha256 = "84682f4ad5a449d0a3ffbc8332200fe8651aee9dd91dcd8d87197ba6c2450dbc"
    path = "lazygit"
    mode = "0700"
[".local/bin/k9s"]
    type = "archive-file"
    url = "https://github.com/derailed/k9s/releases/download/v0.32.7/k9s_Linux_amd64.tar.gz"
    checksum.sha256 = "03934727bfbf39b1e61a74d8e045796cda2de14f8ce4c01df27f43d4494021de"
    path = "k9s"
    mode = "0700"
[".local/bin/rg"]
    type = "archive-file"
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "4cf9f2741e6c465ffdb7c26f38056a59e2a2544b51f7cc128ef28337eeae4d8e"
    path = "ripgrep-14.1.1-x86_64-unknown-linux-musl/rg"
    mode = "0700"
[".local/bin/starship"]
    type = "archive-file"
    url = "https://github.com/starship/starship/releases/download/v1.21.1/starship-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "744e21eb2e61b85b0c11378520ebb9e94218de965bca5b8c2266f6c3e23ff5be"
    path = "starship"
    mode = "0700"
    executable = true
[".local/bin/yq"]
    type = "file"
    url = "https://github.com/mikefarah/yq/releases/download/v4.44.5/yq_linux_amd64"
    checksum.sha256 = "638c4b251c49201fc94b598834b715f8f1c6e9b1854d2820772d2c79f0289002"
    mode = "0700"
    executable = true
{{- end }}
{{- end }}
{{- end }}
