# for excluding externals, add them to ~/.local/share/chezmoi/.chezmoiignore
{{- if eq .chezmoi.os "linux" }}
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/share/fonts/FiraCodeNerdFont-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.tar.xz"
    path = "FiraCodeNerdFont-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "8796ee138a6e7d81487cad381e619381c2ae99ac68d4223ca1a7d82089be38af"
[".local/share/fonts/MesloLGLNerdFontPropo-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Meslo.tar.xz"
    path = "MesloLGLNerdFontPropo-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "d02d9b6e1f35a6bba424399203777b7cea6cbd5ccfded02b0be0393ae89fb598"
# ArchLinux provides those packages already
{{- if and (hasKey .chezmoi.osRelease "id") (not (eq .chezmoi.osRelease.id "arch")) }}
[".local/bin/age-plugin-yubikey"]
    type = "archive-file"
    url = "https://github.com/str4d/age-plugin-yubikey/releases/download/v0.4.0/age-plugin-yubikey-v0.4.0-x86_64-linux.tar.gz"
    checksum.sha256 = "a888596f9c738a9abbe4a28c58b43c691ff3efcd194dafc2aa3e55cbfcd34047"
    path = "age-plugin-yubikey/age-plugin-yubikey"
    mode = "0700"
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/download/v0.17.1/eza_x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "7ece147af0ac636aa11809b631e47988de4fdbbb84810bc32ac3c946133034d9"
    stripComponents = 1
    path = "eza"
    mode = "0700"
[".local/bin/fd"]
    type = "archive-file"
    url = "https://github.com/sharkdp/fd/releases/download/v9.0.0/fd-v9.0.0-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "069e2d58127ddd944c03a2684ad79f72e3f9bd3e0d2642c36adc5b367c134592"
    path = "fd-v9.0.0-x86_64-unknown-linux-musl/fd"
    mode = "0700"
[".local/bin/jless"]
    type = "archive-file"
    url = "https://github.com/PaulJuliusMartinez/jless/releases/download/v0.9.0/jless-v0.9.0-x86_64-unknown-linux-gnu.zip"
    checksum.sha256 = "a1e0eb63ef347adc649989ac5c7d2dc896df6d494622b953c86e3a248e733a93"
    path = "jless"
    mode = "0700"
[".local/bin/lazygit"]
    type = "archive-file"
    url = "https://github.com/jesseduffield/lazygit/releases/download/v0.41.0/lazygit_0.41.0_Linux_x86_64.tar.gz"
    checksum.sha256 = "697a11091362d591e202ec01c76bacf3af692aabeb9656a6bf9b6ff4792259d4"
    path = "lazygit"
    mode = "0700"
[".local/bin/k9s"]
    type = "archive-file"
    url = "https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Linux_amd64.tar.gz"
    checksum.sha256 = "33c31bf5feba292b59b8dabe5547cb52ab565521ee5619b52eb4bd4bf226cea3"
    path = "k9s"
    mode = "0700"
[".local/bin/rg"]
    type = "archive-file"
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "f84757b07f425fe5cf11d87df6644691c644a5cd2348a2c670894272999d3ba7"
    path = "ripgrep-14.1.0-x86_64-unknown-linux-musl/rg"
    mode = "0700"
[".local/bin/yq"]
	type = "file"
	url = "https://github.com/mikefarah/yq/releases/download/v4.42.1/yq_linux_amd64"
	checksum.sha256 = "1a95960dddd426321354d58d2beac457717f7c49a9ec0806749a5a9e400eb45e"
	mode = "0700"
	executable = true
{{- end }}
{{- end }}
