# for excluding externals, add them to ~/.local/share/chezmoi/.chezmoiignore
{{- if eq .chezmoi.os "linux" }}
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/share/fonts/FiraCodeNerdFont-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.tar.xz"
    path = "FiraCodeNerdFont-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "8796ee138a6e7d81487cad381e619381c2ae99ac68d4223ca1a7d82089be38af"
[".local/share/fonts/MesloLGLNerdFontPropo-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Meslo.tar.xz"
    path = "MesloLGLNerdFontPropo-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "d02d9b6e1f35a6bba424399203777b7cea6cbd5ccfded02b0be0393ae89fb598"
# ArchLinux provides those packages already
{{- if and (hasKey .chezmoi.osRelease "id") (not (eq .chezmoi.osRelease.id "arch")) }}
[".local/bin/age-plugin-yubikey"]
    type = "archive-file"
    url = "https://github.com/str4d/age-plugin-yubikey/releases/download/v0.4.0/age-plugin-yubikey-v0.4.0-x86_64-linux.tar.gz"
    checksum.sha256 = "a888596f9c738a9abbe4a28c58b43c691ff3efcd194dafc2aa3e55cbfcd34047"
    path = "age-plugin-yubikey/age-plugin-yubikey"
    mode = "0700"
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/download/v0.17.1/eza_x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "7ece147af0ac636aa11809b631e47988de4fdbbb84810bc32ac3c946133034d9"
    stripComponents = 1
    path = "eza"
    mode = "0700"
[".local/bin/jless"]
    type = "archive-file"
    url = "https://github.com/PaulJuliusMartinez/jless/releases/download/v0.9.0/jless-v0.9.0-x86_64-unknown-linux-gnu.zip"
    checksum.sha256 = "a1e0eb63ef347adc649989ac5c7d2dc896df6d494622b953c86e3a248e733a93"
    path = "jless"
    mode = "0700"
[".local/bin/k9s"]
    type = "archive-file"
    url = "https://github.com/derailed/k9s/releases/download/v0.31.9/k9s_Linux_amd64.tar.gz"
    checksum.sha256 = "075a588642e35cd68394b8ad0df474423650945ef8a786767b7fbce0a4764fea"
    path = "k9s"
    mode = "0700"
{{- end }}
{{- end }}
