# globally shared configuration
geo:
  lat: 52.5
  lon: 13.4
wallpapers:
  target: &wallpaper_target_dir ~/Pictures/Wallpapers
  sources:
    - "https://fedoraproject.org/w/uploads/3/35/F34_default_wallpaper_day.jpg"
    - "https://fedoraproject.org/w/uploads/d/de/F34_default_wallpaper_night.jpg"
    #- src: "https://wallpaperaccess.com/download/abstract-forest-715317"
    #  dst: "wallpaperaccess.com-abstract-forest-715317.jpg"
