{{- if eq .chezmoi.os "linux" }}
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/share/fonts/FiraCodeNerdFont-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.tar.xz"
    path = "FiraCodeNerdFont-Regular.ttf"
    mode = "0600"
# ArchLinux provides those packages already
{{- if and (hasKey .chezmoi.osRelease "id") (not (eq .chezmoi.osRelease.id "arch")) }}
{{ $ageYubikeyVersion := "0.4.0" -}}
{{ $jlessVersion := "0.9.0" }}
[".local/bin/age-plugin-yubikey"]
    type = "archive-file"
    url = "https://github.com/str4d/age-plugin-yubikey/releases/download/v{{ $ageYubikeyVersion }}/age-plugin-yubikey-v{{ $ageYubikeyVersion }}-x86_64-{{ .chezmoi.os }}.tar.gz"
    path = "age-plugin-yubikey/age-plugin-yubikey"
    mode = "0700"
[".local/bin/jless"]
    type = "archive-file"
    url = "https://github.com/PaulJuliusMartinez/jless/releases/download/v{{ $jlessVersion }}/jless-v{{ $jlessVersion }}-x86_64-unknown-linux-gnu.zip"
    path = "jless"
    mode = "0700"
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/download/v0.16.0/eza_x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "abd2b685edb3024d89d5338f214244ab0cea22551606c9469c632a6e018ec4cd"
    stripComponents = 1
    path = "eza"
    mode = "0700"
{{- end }}
{{- end }}
