# for excluding externals, add them to ~/.local/share/chezmoi/.chezmoiignore
{{- if eq .chezmoi.os "linux" }}
[".local/share/fonts/FiraCodeNerdFont-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.tar.xz"
    path = "FiraCodeNerdFont-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "d83fb093e0e05a531cd6f19886a6ceb884a4fa5ea3b53cf099fc1f30c5b3e47d"
[".local/share/fonts/MesloLGLNerdFontPropo-Regular.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Meslo.tar.xz"
    path = "MesloLGLNerdFontPropo-Regular.ttf"
    mode = "0600"
    checksum.sha256 = "a57936d96aefb5cfff0660f3294210ee04705529af6cf811e2274b0923a03939"
# ArchLinux provides those packages already
{{- if and (eq .chezmoi.arch "amd64") (hasKey .chezmoi.osRelease "id") (not (eq .chezmoi.osRelease.id "arch")) }}
[".local/bin/age-plugin-yubikey"]
    type = "archive-file"
    url = "https://github.com/str4d/age-plugin-yubikey/releases/download/v0.5.0/age-plugin-yubikey-v0.5.0-x86_64-linux.tar.gz"
    checksum.sha256 = "019b35a13fc81be56d73d0723db0a2082fbd04c936c2c6836381111f7f51b2c3"
    path = "age-plugin-yubikey/age-plugin-yubikey"
    mode = "0700"
# Void Linux has all these, too
{{- if not ( eq .chezmoi.osRelease.id "void" ) }}
[".local/bin/bat"]
    type = "archive-file"
    url = "https://github.com/sharkdp/bat/releases/download/v0.25.0/bat-v0.25.0-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "93f47d76abe328c402ef712e9ac92aa6d5bc84d5adcbcaf0bbc5665e5275a941"
    stripComponents = 1
    path = "bat"
    mode = "0700"
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/download/v0.21.1/eza_x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "c9ffa0f9fa0c1acc05e9d1ba0efa0296c78cf55d5529a986a809be0ed92b90c2"
    stripComponents = 1
    path = "eza"
    mode = "0700"
[".local/bin/fd"]
    type = "archive-file"
    url = "https://github.com/sharkdp/fd/releases/download/v10.2.0/fd-v10.2.0-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "d9bfa25ec28624545c222992e1b00673b7c9ca5eb15393c40369f10b28f9c932"
    path = "fd-v10.2.0-x86_64-unknown-linux-musl/fd"
    mode = "0700"
[".local/bin/jless"]
    type = "archive-file"
    url = "https://github.com/PaulJuliusMartinez/jless/releases/download/v0.9.0/jless-v0.9.0-x86_64-unknown-linux-gnu.zip"
    checksum.sha256 = "a1e0eb63ef347adc649989ac5c7d2dc896df6d494622b953c86e3a248e733a93"
    path = "jless"
    mode = "0700"
[".local/bin/lazygit"]
    type = "archive-file"
    url = "https://github.com/jesseduffield/lazygit/releases/download/v0.49.0/lazygit_0.49.0_Linux_x86_64.tar.gz"
    checksum.sha256 = "ae9c9a3fcea9cdaf6511a7ca0040210cc71ab481fc773e53737cbfe92da974ce"
    path = "lazygit"
    mode = "0700"
[".local/bin/k9s"]
    type = "archive-file"
    url = "https://github.com/derailed/k9s/releases/download/v0.50.4/k9s_Linux_amd64.tar.gz"
    checksum.sha256 = "1b658c6188339c9f8f271a22339b62d2653da0d636c855629019588d57e5570d"
    path = "k9s"
    mode = "0700"
[".local/bin/rg"]
    type = "archive-file"
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "4cf9f2741e6c465ffdb7c26f38056a59e2a2544b51f7cc128ef28337eeae4d8e"
    path = "ripgrep-14.1.1-x86_64-unknown-linux-musl/rg"
    mode = "0700"
[".local/bin/starship"]
    type = "archive-file"
    url = "https://github.com/starship/starship/releases/download/v1.22.1/starship-x86_64-unknown-linux-musl.tar.gz"
    checksum.sha256 = "62c91b5ecc7f8c8c6ea7ffea42a98bd2e6a2d29daf61562fac04daece18a6461"
    path = "starship"
    mode = "0700"
    executable = true
[".local/bin/yq"]
    type = "file"
    url = "https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64"
    checksum.sha256 = "654d2943ca1d3be2024089eb4f270f4070f491a0610481d128509b2834870049"
    mode = "0700"
    executable = true
{{- end }}
{{- end }}
{{- end }}
