#!/bin/bash
#
# ~/.bashrc - startup file interactive non-login shell
#
# vim:set ts=4 sts=4 sw=4 et ft=bash:

# Source global definitions
if [[ -f /etc/bashrc ]]; then
    # shellcheck disable=SC1091
    source /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# Setup essentials
export BASH_COMPLETION_USER_FILE="$XDG_DATA_HOME"/bash-completion/completions
export HISTCONTROL=ignoreboth
export HISTFILESIZE=2000
export HISTIGNORE="&:ls:[bf]g:exit:pwd:clear:history:sudo *:su *:shred *:jrnl *:[ \t]*"
export HISTSIZE=10000
export HISTTIMEFORMAT="[%Y-%m-%d %T] "
export LESSHISTFILE=/dev/null
export LESSSECURE=1
export WGETRC="$XDG_CONFIG_HOME"/wgetrc

# Make new files unreadable by anyone other than the owner
umask 0077

# Configure interactive sessions
if [[ $- == *i* ]]; then

    # Establish generic aliases
    alias diff='diff -au --color=auto'
    alias grep='grep --color=auto'
    alias psc='ps xawf -eo pid,user,cgroup,args'
    alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'

    # Add XDG_BIN_PATH to $PATH if set
    if [[ -n "$XDG_BIN_HOME" ]] && [[ ":$PATH:" != *":$XDG_BIN_HOME:"* ]]; then
        PATH="$XDG_BIN_HOME:$PATH"
    fi

    # Set up direnv hooks to load/unload environment on current folder
    if [[ -x $(type -p direnv) ]]; then
        eval "$(direnv hook bash)"
    fi

    # Modern ls replacement - https://github.com/eza-community/eza
    if [[ -x $(type -p eza) ]]; then
        alias ls='eza --group-directories-first'
        alias ll='ls -l --icons'
        alias la='ls -la'
    fi

    # Source user specific files if running interactively
    if [[ -d "$XDG_DATA_HOME"/bash ]]; then
        for rc in "$XDG_DATA_HOME"/bash/*.sh; do
            if [[ -f "$rc" ]]; then
                # shellcheck disable=SC1090
                . "$rc"
            fi
        done
    fi
fi
