#!/bin/bash
# ~/.bashrc
#
# vim: ts=4 sts=4 sw=4 et ft=bash:

# Source global definitions
if [[ -f /etc/bashrc ]]; then
    # shellcheck disable=SC1091
    source /etc/bashrc
fi

# User specific environment

# Set up XDG_* configuration, ensuring its available everywhere
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME"/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME"/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME"/.local/share}
export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
export XDG_STATE_HOME=${XDG_STATE_HOME:-"$HOME"/.local/state}

# Add locally installed binaries to PATH
if ! [[ "$PATH" =~ "$HOME"/.local/bin: ]]; then
    PATH="$HOME/.local/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# Make new files unreadable by anyone other than the owner
umask 0077

# Source user specific files if running interactively
if [[ $- == *i* && -d ~/.bashrc.d ]]; then
    for rc in ~/.bashrc.d/*.sh; do
        if [[ -f "$rc" ]]; then
            # shellcheck disable=SC1090
            . "$rc"
        fi
    done

    unset rc
fi
