" With inspirations from:
" https://git.sr.ht/~sircmpwn/dotfiles/tree/master/.vimrc
" https://stackoverflow.com/questions/1878974/redefine-tab-as-4-spaces#1878983
" https://vim.fandom.com/

" basic settings
set clipboard=unnamed   " share access to system clipboard
set encoding=utf-8      " assume utf-8 by default
set ff=unix             " default to unix line endings
set history=1000        " save long history
set laststatus=2        " always show bottom footer
set nocompatible        " disable legacy mode
set showcmd             " show what you're typing as a command
set t_Co=256            " force 256 color mode

" folding
set foldmethod=marker

" search
set hlsearch            " highlight all search results
set ignorecase          " do case insensitive search
set incsearch           " show incremental search results as you type
set showmatch           " show matches in document
set smartcase           " search case insensitive matches

" map CTRL-c, v, p
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <C-r><C-o>+

" syntax highlighting
filetype on
filetype plugin on
syntax enable
colorscheme onedark

" indent settings
set noautoindent        " do *not* take indent from previous line
set expandtab           " insert spaces for tabs in insert mode
set smarttab            " smart tab handling based on expandtab setting
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Cool tab completion stuff
set wildmenu
set wildmode=list:longest,full

" Enable mouse support in console
if has('mouse')
    set mouse=a
endif

" Set spell-check
try
    autocmd BufNewFile,BufRead *.md setlocal spell spelllang=en
    autocmd BufNewFile,BufRead *.txt setlocal spell spelllang=en
    catch
endtry

" find trailing whitespace
match ErrorMsg '\s\+$'

" backup settings
set backup              " force writing backups
set noswapfile          " disable swap file
if has('writebackup')
    set backupdir=$XDG_RUNTIME_DIR/.vim/backup
    if filewritable(&backupdir) != 2
        call mkdir(&backupdir, 'p', 0700) " create backup directory if it doesn't exist
    endif
endif

" undo setting
if has('persistent_undo')
    set undofile
    set undodir=$XDG_RUNTIME_DIR/.vim/undo
    if filewritable(&undodir) != 2
        call mkdir(&undodir, 'p', 0700) " create undo directory if it doesn't exist
    endif
    set undolevels=1000
    set undoreload=10000
endif

" PLUGINS ---------------------------------------------------------------- {{{

"Fonts for the Status Line
let g:airline_powerline_fonts = 1

" }}}
