# Set up globally available XDG_* configuration
XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
# unofficial variable, used by e.g. github.com/bevry/dorothy
XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"

# add XDG_BIN_PATH & XDG_DATA_HOME
PATH=$XDG_BIN_HOME:$PATH
#XDG_DATA_DIRS=${XDG_DATA_DIRS}:${XDG_DATA_HOME}

# Setup screenshot folder, see `man grimshot`
# should also work by setting it in xdg-users.dir
# but might not be exported to flatpak packages
XDG_SCREENSHOTS_DIR=${HOME}/Pictures/Screenshots
