# hint for electron-based apps, removed in Electron >=38
ELECTRON_OZONE_PLATFORM_HINT=wayland
# hint for QT-based apps, https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QGtk3Style
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=gtk3
