wallpaper:
  light: &wallpaper_light ~/Pictures/Wallpapers/F34_default_wallpaper_day.jpg
  dark: &wallpaper_dark ~/Pictures/Wallpapers/F34_default_wallpaper_night.jpg
sway:
  outputs:
    - name: "eDP-1"
      comment: "built-in"
      config:
        - pos 300 1440
    - name: &output_office "Dell Inc. DELL S2722QC 7GZYLD3"
      comment: "office"
      config:
        - resolution 3840x2160
        - scale 1.5
        - pos 0 0
    - name: &output_standing_desk "Dell Inc. DELL P2720DC 9K0QK53"
      comment: "standing desk"
      config:
        - resolution 2560x1440
        - pos 0 0
    - name: &output_workstation "LG Electronics LG ULTRAWIDE 508NTYTND626"
      comment: "workstation"
      config:
        - pos -440 0
  colorschemes:
    dunst:
      link: &dunst_theme_target ~/.config/dunst/dunstrc.d/10-colorscheme.conf
      light:
        name: light
        icon: weather-clear
        source: ~/.config/dunst/dunstrc.d/tokyonight_day.ini
        target: *dunst_theme_target
      dark:
        name: dark
        icon: weather-clear-night
        source: ~/.config/dunst/dunstrc.d/tokyonight_moon.ini
        target: *dunst_theme_target
    rofi:
      link: &rofi_theme_target ~/.config/rofi/themes/selected-colorscheme.rasi
      light:
        source: ~/.config/rofi/themes/spotlight.rasi
        target: *rofi_theme_target
      dark:
        source: ~/.config/rofi/themes/spotlight-dark.rasi
        target: *rofi_theme_target
    swaylock:
      link: &swaylock_target ~/Pictures/Wallpapers/swaylock.wallpaper
      light:
        source: *wallpaper_light
        target: *swaylock_target
      dark:
        source: *wallpaper_dark
        target: *swaylock_target
    wallpaper:
      light:
        - output: "*"
          image: *wallpaper_light
        - output: *output_office
          image: ~/Pictures/Wallpapers/default-prefer-light.wallpaper
        - output: *output_workstation
          image: ~/Pictures/Wallpapers/Lakeside_2019_Teal_WQHD.jpg
      dark:
        - output: "*"
          image: *wallpaper_dark
        - output: *output_office
          image: ~/Pictures/Wallpapers/default-prefer-dark.wallpaper
        - output: *output_workstation
          image: ~/Pictures/Wallpapers/Lakeside_2019_Evening_WQHD.jpg
    waybar:
      link: &waybar_theme_target ~/.config/waybar/themes/current.css
      light:
        source: ~/.config/waybar/themes/tokyonight_day.css
        target: *waybar_theme_target
      dark:
        source: ~/.config/waybar/themes/tokyonight_night.css
        target: *waybar_theme_target

